[2025-09-25T08:06:45.734+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bronze_to_silver.transform_to_gold_full manual__2025-09-25T08:06:36.436158+00:00 [queued]>
[2025-09-25T08:06:45.736+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bronze_to_silver.transform_to_gold_full manual__2025-09-25T08:06:36.436158+00:00 [queued]>
[2025-09-25T08:06:45.736+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-09-25T08:06:45.741+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform_to_gold_full> on 2025-09-25 08:06:36.436158+00:00
[2025-09-25T08:06:45.744+0000] {standard_task_runner.py:57} INFO - Started process 319 to run task
[2025-09-25T08:06:45.745+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'bronze_to_silver', 'transform_to_gold_full', 'manual__2025-09-25T08:06:36.436158+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/fetch _player_stats.py', '--cfg-path', '/tmp/tmpw6tzmgrk']
[2025-09-25T08:06:45.746+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask transform_to_gold_full
[2025-09-25T08:06:45.759+0000] {task_command.py:416} INFO - Running <TaskInstance: bronze_to_silver.transform_to_gold_full manual__2025-09-25T08:06:36.436158+00:00 [running]> on host 1afec62875aa
[2025-09-25T08:06:45.781+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_eng' AIRFLOW_CTX_DAG_ID='bronze_to_silver' AIRFLOW_CTX_TASK_ID='transform_to_gold_full' AIRFLOW_CTX_EXECUTION_DATE='2025-09-25T08:06:36.436158+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-25T08:06:36.436158+00:00'
[2025-09-25T08:06:45.794+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fetch _player_stats.py", line 115, in transform_silver_to_gold_full
    df[gold_columns].to_sql("player_stats_gold", engine, if_exists="replace", index=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3767, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5877, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5941, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['pass_accuracy_percent'] not in index"
[2025-09-25T08:06:45.797+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=bronze_to_silver, task_id=transform_to_gold_full, execution_date=20250925T080636, start_date=20250925T080645, end_date=20250925T080645
[2025-09-25T08:06:45.801+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 19 for task transform_to_gold_full ("['pass_accuracy_percent'] not in index"; 319)
[2025-09-25T08:06:45.808+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-09-25T08:06:45.813+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
